const spotsData = [{id:1,name:'图书馆穹顶',category:'校园地标',emoji:'📚',description:'日出时分魔法光影——清晨的阳光透过穹顶洒下，在地面形成美丽的光斑，是学习打卡的绝佳地点。图书馆不仅是知识的殿堂，更是校园最美的建筑之一。'},{id:2,name:'樱花大道',category:'自然风光',emoji:'🌸',description:'春日限定浪漫花海——每年春季，樱花盛开，整条大道被粉色覆盖，微风拂过，花瓣纷飞，仿佛置身童话世界，是拍照打卡的必去之地。'},{id:3,name:'食堂三楼露台',category:'美食角落',emoji:'🍜',description:'边吃美食边看日落——在这里可以品尝各种美味小吃，同时欣赏美丽的校园日落景色，是放松身心、享受美食的好地方。'},{id:4,name:'钟楼广场',category:'校园地标',emoji:'⏰',description:'百年历史毕业照必拍——钟楼见证了学校的百年变迁，钟声回荡在整个校园，是毕业季拍照留念的标志性地点。'},{id:5,name:'湖畔凉亭',category:'休闲空间',emoji:'🪷',description:'晨读约会绝佳去处——湖边的凉亭宁静优美，清晨适合晨读学习，傍晚适合约会散步，感受大自然的美好。'},{id:6,name:'涂鸦墙',category:'文艺空间',emoji:'🎨',description:'学生原创艺术作品——这里展示了同学们的创意和才华，每一幅涂鸦都是独特的艺术表达，是校园里最有个性的角落。'},{id:7,name:'星空观测台',category:'特色体验',emoji:'🌌',description:'专业望远镜观星——配备专业天文望远镜，可以清晰观测星空、月亮和行星，是探索宇宙奥秘的绝佳体验。'}];
const spotsGrid = document.getElementById('spotsGrid');
const categoryBtns = document.querySelectorAll('.category-btn');
const modalOverlay = document.getElementById('modalOverlay');
const modalClose = document.getElementById('modalClose');
function renderSpots(filteredSpots){spotsGrid.innerHTML='';filteredSpots.forEach((spot,index)=>{const card=document.createElement('div');card.className='spot-card';card.style.animationDelay=`${index*0.1}s`;card.innerHTML=`<div class="spot-image"><span class="spot-emoji">${spot.emoji}</span></div><div class="spot-content"><div class="spot-header"><h3 class="spot-title">${spot.name}</h3><span class="spot-category">${spot.category}</span></div><p class="spot-desc">${spot.description.substring(0,60)}...</p></div>`;card.addEventListener('click',()=>openModal(spot));spotsGrid.appendChild(card);});}
function openModal(spot){document.getElementById('modalEmoji').textContent=spot.emoji;document.getElementById('modalTitle').textContent=spot.name;document.getElementById('modalCategory').textContent=spot.category;document.getElementById('modalDesc').textContent=spot.description;modalOverlay.classList.add('active');document.body.style.overflow='hidden';}
function closeModal(){modalOverlay.classList.remove('active');document.body.style.overflow='';}
categoryBtns.forEach(btn=>{btn.addEventListener('click',()=>{categoryBtns.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const category=btn.dataset.category;if(category==='all'){renderSpots(spotsData);}else{const filtered=spotsData.filter(spot=>spot.category===category);renderSpots(filtered);}});});
modalClose.addEventListener('click',closeModal);
modalOverlay.addEventListener('click',(e)=>{if(e.target===modalOverlay){closeModal();}});
document.addEventListener('keydown',(e)=>{if(e.key==='Escape'&&modalOverlay.classList.contains('active')){closeModal();}});
document.addEventListener('DOMContentLoaded',()=>{renderSpots(spotsData);});